services:
  otrecorder:
    container_name: lucos_locations_otrecorder
    image: owntracks/recorder
    volumes:
      - store:/store
      - config:/config
    restart: always
    environment:
      - OTR_HOST=mqtt
      - OTR_PORT=1883
      - OTR_HTTPPORT=8083 # Runs HTTP on default port
      - OTR_GEOKEY
      - OTR_USER=${RECORDER_USERNAME}
      - OTR_PASS=${RECORDER_PASSWORD}
    depends_on:
      - mqtt
  otfrontend:
    container_name: lucos_locations_otfrontend
    build: ./otfrontend
    image: lucas42/lucos_locations_otfrontend
    ports:
      - "8028:80"
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
      - OT_USERNAME
      - OT_PASSWORD
    restart: always
    depends_on:
      - otrecorder
  mqtt:
    container_name: lucos_locations_mosquitto
    build: ./mosquitto
    image: lucas42/lucos_locations_mosquitto
    restart: always
    ports:
      - "8883:8883"
    environment:
      - OT_USERNAME
      - OT_PASSWORD
      - RECORDER_USERNAME
      - RECORDER_PASSWORD
    volumes:
      - "mosquitto_data:/mosquitto/data"
      - "mosquitto_log:/mosquitto/log"
      - "letsencrypt:/etc/letsencrypt"

volumes:
  store:
  config:
  mosquitto_data:
  mosquitto_log:
  letsencrypt:
    external: true
    name: lucos_router_letsencrypt