# Run as the mosquitto user (which is in the certreaders group for TLS key access)
user mosquitto

# Security
allow_anonymous false
password_file /mosquitto/config/passwords
require_certificate false

# Operability
persistence false
log_dest stdout

# MQTT Default listener (only available locally)
listener 1883

# MQTT over TLS
listener 8883
certfile /etc/letsencrypt/live/locations.l42.eu/fullchain.pem
keyfile /etc/letsencrypt/live/locations.l42.eu/privkey.pem
